FROM nginx:alpine

# Nginx 설정 파일을 복사
COPY ./nginx.https.conf /etc/nginx/conf.d/default.conf

# 빌드된 React 파일들 (index.html 포함) 복사
COPY ./ /usr/share/nginx/html

# 인증서 관련 파일은 도커 컴포즈에서 마운트되므로 여기서는 추가 설정 불필요

# 컨테이너가 80번 포트와 443번 포트를 외부에 노출
EXPOSE 80 443

# Nginx 실행
CMD ["nginx", "-g", "daemon off;"]
