version: '3'
services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.https.conf:/etc/nginx/conf.d/default.conf:ro  # Nginx 설정 파일 마운트
      - /etc/letsencrypt:/etc/letsencrypt:ro  # SSL 인증서 디렉토리 마운트
      - .:/usr/share/nginx/html  # 현재 디렉토리 (최상단) 마운트, index.html 포함
      - /var/www/certbot:/var/www/certbot  # Certbot 인증서 발급을 위한 경로 마운트
    environment:
      - TZ=Asia/Seoul
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
